// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkFlow.Context;

namespace WorkFlow.Migrations
{
    [DbContext(typeof(WFContext))]
    [Migration("20201219203501_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("WorkFlow.Entities.WF", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CurrentProgressNumberWFStep")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WFStatusId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("WFStatusId");

                    b.ToTable("WorkFlows");
                });

            modelBuilder.Entity("WorkFlow.Entities.WFStatus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("WFStatus");
                });

            modelBuilder.Entity("WorkFlow.Entities.WFStep", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("IsFinal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirst")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("WFId")
                        .HasColumnType("int");

                    b.Property<int>("WFStatusId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("WFId");

                    b.HasIndex("WFStatusId");

                    b.ToTable("WFSteps");
                });

            modelBuilder.Entity("WorkFlow.Entities.WFTask", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WFId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("WFId");

                    b.ToTable("WFTasks");
                });

            modelBuilder.Entity("WorkFlow.Entities.WF", b =>
                {
                    b.HasOne("WorkFlow.Entities.WFStatus", "WFStatus")
                        .WithMany()
                        .HasForeignKey("WFStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("WFStatus");
                });

            modelBuilder.Entity("WorkFlow.Entities.WFStep", b =>
                {
                    b.HasOne("WorkFlow.Entities.WF", "WorkFlow")
                        .WithMany("WFSteps")
                        .HasForeignKey("WFId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WorkFlow.Entities.WFStatus", "WFStatus")
                        .WithMany()
                        .HasForeignKey("WFStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("WFStatus");

                    b.Navigation("WorkFlow");
                });

            modelBuilder.Entity("WorkFlow.Entities.WFTask", b =>
                {
                    b.HasOne("WorkFlow.Entities.WF", "WorkFlow")
                        .WithMany("WFTasks")
                        .HasForeignKey("WFId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("WorkFlow");
                });

            modelBuilder.Entity("WorkFlow.Entities.WF", b =>
                {
                    b.Navigation("WFSteps");

                    b.Navigation("WFTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
